#!/bin/bash

set -o pipefail

cd /opt/SolarEdge/solaredge || exit 99

INTERFACE=enx0023573c8964
INTERFACE=eth0

DATA=/data/SolarEdge

CAPDIR=$DATA/pcap
JSONDIR=$DATA/json
LOGDIR=$DATA/log
FLDIR=$DATA/firstAndLast
STATDIR=$DATA

DATE=0
while [ $DATE < 20190000 ]; do
  sleep 1
  DATE=`date +%Y%m%d`
done

PIPE=/tmp/secapture-pipe
SMLPIPE=/tmp/sml-pipe

rm -f $PIPE
mkfifo $PIPE

rm -f $SMLPIPE
mkfifo $SMLPIPE

while read smlline; do 
        if [ "${smlline:0:1}" = "{" ]; then
	        echo "$smlline"  >> $JSONDIR/sml-$DATE.jsons
		if [ ! -f $FLDIR/$DATE-first-sml.json ]; then
                  echo "$smlline"  > $FLDIR/$DATE-first-sml.json
                fi
		echo "$smlline"  > $FLDIR/$DATE-last-sml.json.tmp
		mv $FLDIR/$DATE-last-sml.json.tmp $FLDIR/$DATE-last-sml.json
        	echo "$smlline"  > $STATDIR/sml.json.tmp
	        mv $STATDIR/sml.json.tmp $STATDIR/sml.json
	fi
done <$SMLPIPE &

echo "sml pipe reader running"

java -Djava.library.path=/usr/lib/jni -jar ../sml/SmartMeterReader-20181231-1.jar /dev/ttyUSB1 2>>$LOGDIR/sml-$DATE.log >>$SMLPIPE &

echo "smlreader running"

python semonitor.py -vvvv \
		-d $LOGDIR/$DATE.log \
		-k BE040526.key \
		-a <$PIPE | \
	tee $JSONDIR/$DATE.json | \
	python se2state.py -o $STATDIR/solar.json &

echo "reader running" >&2

d=`stat -c "%y" last0503.msg | cut -f 1 -d\ `
d=${d//-}

if [ $d != $DATE ]; then
  if [ -f $CAPDIR/$d.pcap ]; then
    echo "old file $d.pcap catted" >&2
    tshark -r $CAPDIR/$DATE.pcap -T fields -e data | xxd -r -p >>$PIPE
  fi
  if [ -f $CAPDIR/$d.pcap.gz ]; then
    echo "old file $d.pcap.gz catted" >&2
    zcat $CAPDIR/$d.pcap.gz tshark -r - -T fields -e data | xxd -r -p >>$PIPE
  fi
fi

if [ -f $CAPDIR/$DATE.pcap ]; then
  echo "old file $DATE.pcap catted" >&2
  tshark -r $CAPDIR/$DATE.pcap -T fields -e data | xxd -r -p >>$PIPE
fi

echo "begin to dump" >&2
/usr/sbin/tcpdump --time-stamp-precision=micro -i $INTERFACE -U -w - tcp | \
	tee -a $CAPDIR/$DATE.pcap | \
	tshark -r - -T fields -e data | xxd -r -p >>$PIPE

