#!/bin/bash

cd /opt/SolarEdge/solaredge || exit 99

INTERFACE=enx0023573c8964

DATA=/data/SolarEdge

CAPDIR=$DATA/pcap
JSONDIR=$DATA/json
LOGDIR=$DATA/log
STATDIR=$DATA

DATE=`date +%Y%m%d`

/usr/sbin/tcpdump -i $INTERFACE -U -w - tcp | \
	tee -a $CAPDIR/$DATE.pcap | \
	python seextract.py | \
	python semonitor.py -vvv \
		-d $LOGDIR/$DATE.log \
		-k 7E19F79D.key \
		-a | \
	tee -a $JSONDIR/$DATE.json | \
	python se2state.py -o $STATDIR/solar.json
