#!/bin/bash

set -o pipefail

cd /opt/SolarEdge/solaredge || exit 99

INTERFACE=enx0023573c8964

DATA=/data/SolarEdge

CAPDIR=$DATA/pcap
JSONDIR=$DATA/json
LOGDIR=$DATA/log
STATDIR=$DATA

DATE=`date +%Y%m%d`

/usr/sbin/tcpdump -i $INTERFACE -U -w - tcp | \
	tee -a $CAPDIR/$DATE.pcap | \
	python semonitor.py \
		-d $LOGDIR/$DATE.log \
		-k 7E19F79D.key \
		-a | \
        cat $JSONDIR/$DATE.json - | \
	tee -a $JSONDIR/$DATE.json | \
	python se2state-as.py -o $STATDIR/solar.json
