#!/bin/bash -

INTERFACE=enx0023573c8964
ROOTDIR=/data/SolarEdge/json

# wait for the time to get set
while [ `date +%Y` == "1969" ]
do
	echo "Waiting for correct time"
	sleep 1
done

tail -f $ROOTDIR/`date +%Y%m%d`.json | python se2state.py -o $ROOTDIR/solar.json
